# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SsS0IT-XyVBupfKoIiVGXnVrkEvo6MXQ
"""

print('hello python world')

message = 'hello python world'
print(message)

message = 'hello python world!'
print(message)

message = 'hello python crash course world'
print(message)

#say hello to everyone
print('hello python world')

simpleMessage = ('hello')
print(simpleMessage)

simpleMessage = ('hello')
print(simpleMessage)
simpleMessage = ('hi and hello')
print(simpleMessage)

name = 'ada lovelace'
print(name.title())

name = 'Ada Lovelace'
print(name.upper())
print(name.lower())

first_name = 'ada'
last_name = 'lovelace'
full_name = f'{first_name}{last_name}'
print(f'Hello, {full_name.title()}!')

first_name = 'ada'
last_name = 'lovelace'
full_name = f'{first_name}{last_name}'
message = (f'Hello, {full_name.title()}!')
print(message)

eric = ('hello eric')
print(eric )

name = 'Eric'
print(name.upper())
print(name.lower())
print(name.title())

#going through this like this is actully helping
name_author = 'Shakespeer,'
quoteOf_author = '"to be or not to be that is the question"'
allTogether_author = f'{name_author}{quoteOf_author}'
print(allTogether_author)

famous_person = 'Shakespeer,'
quoteOf_author = '"to be or not to be that is the question"'
allTogether_author = f'{famous_person}{quoteOf_author}'
message = allTogether_author
print(message)

#was a tad confused on what the book was fully asking on this
name_something = ' random '

print(name_something.rstrip())

print(name_something.lstrip())

print(name_something.strip())

filename = 'pyhton_notes.txt'
print(filename.removesuffix('txt'))

2+3

3-2

2*3

3/2

3**2

3**3

10**6

2+3*4

(2+3)*4

0.1+0.1

0.2+0.1

1+2.0

universal_age = 14_000_000_000
print(universal_age)

print(4+4)
print(16-8)
print(2*4)
print(64/8)

x_y = 10
message = f'favorit number is {x_y}'
print (message)

import this

import turtle